version: "3.9"

services:

    mongo: 
        image: mongo
        ports:
            - 5001:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    
    postgres:
        image: postgres
        ports:
            - 5002:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root

    coordinator:
        build: ./coordinator
        volumes:
            - ./coordinator:/usr/src/coordinator
        ports:
            - 5000:80
        depends_on:
            - mongo
            - postgres