version: '3.9'
services:
  mongo:
    image: mongo
    ports:
      - '5002:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  postgres:
    image: postgres
    ports:
      - '5003:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  mlflow-server:
    build: ./mlflow-server
    volumes:
      - ./mlflow-data:/usr/src/mlfs-app/mlflow-data/
    expose:
      - '5000'
    ports:
      - '5004:5000'
    depends_on:
      - postgres
  mlflow-ui:
    build: ./mlflow-ui
    volumes:
      - ./mlflow-data:/usr/src/mlfui-app/mlflow-data/
    expose:
      - '5000'
    ports:
      - '5005:5000'
    depends_on:
      - postgres
      - mlflow-server
  coordinator:
    build: ./coordinator
    volumes:
      - './coordinator:/usr/src/coordinator'
    ports:
      - '5001:8085'
    depends_on:
      - mongo
      - postgres
      - mlflow-server
      - mlflow-ui