version: '3.9'
services:

  mongo:
    image: mongo
    ports:
      - '5002:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  postgres:
    image: postgres
    ports:
      - '5003:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  coordinator:
    build: ./coordinator
    volumes:
      - ./coordinator/.aim/:/usr/src/app/.aim/
    ports:
      - '5001:8085'
      - '5009:43800'
    depends_on:
      - mongo
      - postgres